In [1]:
import pandas as pd

df = pd.read_csv('public_street_lighting.csv')
df.drop(columns=['UNITNO'], inplace=True)

In [2]:
print(df)

       EASTING  NORTHING
0       422259    529266
1       422228    529240
2       422214    529216
3       422203    529189
4       422157    529259
5       422237    529254
6       425459    554220
7       425450    554184
8       425432    554148
9       425417    554124
10      425411    554088
11      417145    516985
12      417136    516958
13      417130    516931
14      417135    516913
15      417133    516887
16      419613    534958
17      419623    534974
18      419634    534953
19      442259    549970
20      442260    549945
21      442231    549953
22      442364    550017
23      442369    549984
24      442383    549974
25      442356    549971
26      442339    549961
27      442405    549995
28      426334    525013
29      427863    553683
...        ...       ...
83703   425675    525286
83704   425735    525265
83705   425858    525235
83706   425838    525193
83707   425833    525216
83708   407313    517974
83709   433193    531524
83710   401333    519469


In [3]:
import matplotlib.pyplot as plt

from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.preprocessing import StandardScaler
X = StandardScaler().fit_transform(df)


C:\Users\Michael Deng\Anaconda3\lib\site-packages\sklearn\preprocessing\data.py:645: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
C:\Users\Michael Deng\Anaconda3\lib\site-packages\sklearn\base.py:464: DataConversionWarning: Data with input dtype int64 were all converted to float64 by StandardScaler.
  return self.fit(X, **fit_params).transform(X)


In [4]:
from sklearn.cluster import DBSCAN
from sklearn import metrics
db = DBSCAN(eps=0.2, min_samples=10).fit(X)

In [ ]:
import numpy as np

core_samples_mask = np.zeros_like(db.labels_, dtype=bool)
core_samples_mask[db.core_sample_indices_] = True
labels = db.labels_
    
# Number of clusters in labels, ignoring noise if present.
n_clusters_ = len(set(labels)) - (1 if -1 in labels else 0)

# #############################################################################
# Plot result
import matplotlib.pyplot as plt

# Black removed and is used for noise instead.
unique_labels = set(labels)
colors = [plt.cm.Spectral(each)
          for each in np.linspace(0, 1, len(unique_labels))]
for k, col in zip(unique_labels, colors):
    if k == -1:
        # Black used for noise.
        col = [0, 0, 0, 1]

    class_member_mask = (labels == k)

    xy = X[class_member_mask & core_samples_mask]
    print(xy)
    print(X)
    plt.plot(xy[:, 0], xy[:, 1], 'o', markerfacecolor=tuple(col),
             markeredgecolor='k', markersize=14)

    xy = X[class_member_mask & ~core_samples_mask]
    plt.plot(xy[:, 0], xy[:, 1], 'o', markerfacecolor=tuple(col),
             markeredgecolor='k', markersize=6)

plt.title('Estimated number of clusters: %d' % n_clusters_)
plt.show()

[[-0.32311188 -1.14858923]
 [-0.3261049  -1.15123418]
 [-0.32745659 -1.15367567]
 ...
 [ 0.2430523   1.01630015]
 [ 0.24392124  1.01396039]
 [ 0.24507983  1.01182409]]
[[-0.32311188 -1.14858923]
 [-0.3261049  -1.15123418]
 [-0.32745659 -1.15367567]
 ...
 [ 0.2430523   1.01630015]
 [ 0.24392124  1.01396039]
 [ 0.24507983  1.01182409]]
[[-3.88490632e+00 -4.75124489e-03]
 [-3.89282335e+00 -1.48223905e-02]
 [-3.76016483e+00 -1.80335056e-01]
 [-3.85323820e+00 -9.46794539e-02]
 [-3.83518351e+00 -1.29470684e-01]
 [-3.84030062e+00 -1.03122940e-01]
 [-3.84561082e+00 -1.05157515e-01]
 [-3.86260347e+00 -2.00456882e-03]
 [-3.78430211e+00 -1.53682125e-01]
 [-3.80197061e+00 -1.42186777e-01]
 [-3.80959799e+00 -1.35574409e-01]
 [-3.82398381e+00 -1.27436109e-01]
 [-3.83392837e+00 -1.27130923e-01]
 [-3.70233189e+00 -1.93254606e-01]
 [-3.88374773e+00 -6.82095154e-04]
 [-3.83199739e+00 -1.24791162e-01]
 [-3.34230014e+00 -2.40660201e-01]
 [-3.70358703e+00 -1.77283193e-01]
 [-3.62335469e+00 -2.38218711e-01]

[[-1.68850986 -0.33567485]
 [-1.75010821 -0.35479985]
 [-1.77028699 -0.22540089]
 [-1.74141879 -0.32367086]
 [-1.73427415 -0.31593947]
 [-1.73639824 -0.31482045]
 [-1.73832922 -0.31370144]
 [-1.74054985 -0.31441354]
 [-1.74363942 -0.31441354]
 [-1.74537731 -0.31370144]
 [-1.79519666 -0.32957112]
 [-1.73736373 -0.33140224]
 [-1.76632847 -0.22804584]
 [-1.70714385 -0.32865556]
 [-1.71042652 -0.32000862]
 [-1.69922682 -0.32763828]
 [-1.71187475 -0.27819811]
 [-1.70733694 -0.28094478]
 [-1.701544   -0.28501393]
 [-1.70019231 -0.29040556]
 [-1.70231639 -0.29823867]
 [-1.70231639 -0.30515622]
 [-1.70193019 -0.31339625]
 [-1.70164054 -0.32255184]
 [-1.70144745 -0.33221607]
 [-1.75416328 -0.36415889]
 [-1.7457635  -0.34004918]
 [-1.70984722 -0.32723136]
 [-1.71042652 -0.33069014]
 [-1.79761039 -0.34157511]
 [-1.72133657 -0.32468814]
 [-1.71950214 -0.27911367]
 [-1.76362509 -0.24411898]
 [-1.76236996 -0.2222473 ]
 [-1.75464602 -0.36710903]
 [-1.7178608  -0.30993747]
 [-1.71438503 -0.33221607]
 